---
- name: Install elasticsearch
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ packages_elasticsearch_EL7 }}"

- name: configure elastic search cluster name
  replace: 
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '.*cluster.name: .*' 
    replace: 'cluster.name: {{graylog2_cluster_name}}' 

- name: configure elasticsearch hostname
  replace: 
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: '.*network.host: .*' 
    replace: 'network.host: localhost' 

- name: Enable and start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
...
